variables:
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.uv-cache"
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: none
  TRIVY_CACHE_DIR: ".trivycache/"
  TRIVY_VERSION: "0.70.0"


.basic_template:
  image: troi-docker-ci:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "development"'
      when: always
    - if: '$CI_MERGE_REQUEST_ID'
      when: always
    - when: never

.trivy_setup:
  extends: .basic_template
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v$TRIVY_VERSION
    - cd "$CI_PROJECT_DIR"
  cache:
    paths:
      - $TRIVY_CACHE_DIR

.base_template:
  extends: .basic_template
  before_script:
    - cd "$CI_PROJECT_DIR"
    - export UV_PYTHON=$(which python)
    # install deps into container venv
    - uv sync --all-extras --cache-dir "$UV_CACHE_DIR"
    - uv pip install ruff coverage
    - uv run ruff --version
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR

.unittest_template:
  extends: .base_template
  script:
    - uv pip install coverage
    - cd tests
    - uv run coverage run -m test_suite
    - uv run coverage report --omit="*/_remote_module_non_scriptable*"
    - uv cache prune --ci
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

.linter_template:
  extends: .base_template
  script:
    - uv run ruff check --config pyproject.toml --output-format=gitlab > code-quality-report.json
    - uv cache prune --ci
  artifacts:
    expire_in: 1 week
    reports:
      codequality: code-quality-report.json

.formatter_template:
  extends: .base_template
  script:
    - uv run ruff format --config pyproject.toml --diff
    - uv cache prune --ci

.check_dependencies:
  extends: .base_template
  script:
    - uv pip install check-dependencies
    - uv run check-dependencies --all ./src
    - uv cache prune --ci

.check_vulnerabilities:
  extends: .trivy_setup
  script:
    - uv run trivy fs --exit-code 1 --severity HIGH,CRITICAL --cache-dir $TRIVY_CACHE_DIR .

.check_licenses:
  extends: .trivy_setup
  before_script:
    - !reference [".trivy_setup", "before_script"]
    # install deps into container venv
    # https://trivy.dev/docs/latest/scanner/license/#license-scanning
    - export UV_PYTHON=$(which python)
    - uv sync --all-extras --cache-dir "$UV_CACHE_DIR"
  script:
    - uv run trivy fs --scanners license --exit-code 0 --cache-dir $TRIVY_CACHE_DIR .
  artifacts:
    when: always
    reports:
      license_scanning: license-scanning-report.json
    paths:
      - license-scanning-report.json
